### ISSUE TITLE
KeyError: 'pixel_values'

### ISSUE THREAD

**Issue by HMacro** [2U1/Llama3.2-Vision-Finetune#1]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/dyh/anaconda3/envs/llama3.2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/dyh/anaconda3/envs/llama3.2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/dyh/anaconda3/envs/llama3.2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/dyh/llama3.2/finetune/src/training/data.py", line 119, in __getitem__
    pixel_values = inputs['pixel_values']
  File "/data/dyh/anaconda3/envs/llama3.2/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 87, in __getitem__
    return self.data[item]
KeyError: 'pixel_values'

I encountered the above error during execution. How can I resolve it?

**Comment by 2U1** [comment]
Maybe the issue is caused by having no image in your data.
This does not accept text-only data for now.

**Comment by 2U1** [comment]
I'll try to update for text-only data too.
